// Reference data for the admin "new category" form: popular phone brands and
// their models, newest → oldest. The brand/model fields are searchable but also
// accept free-typed values, so this list is a convenience, not a hard limit —
// anything missing or brand-new can still be typed in directly.

export const PHONE_BRANDS = [
  "Apple",
  "Samsung",
  "Google",
  "OnePlus",
  "Motorola",
  "Xiaomi",
  "Oppo",
  "Sony",
  "Nokia",
  "Asus",
  "LG",
] as const;

export const PHONE_MODELS: Record<string, string[]> = {
  Apple: [
    "iPhone 17 Pro Max",
    "iPhone 17 Pro",
    "iPhone 17 Air",
    "iPhone 17",
    "iPhone 16e",
    "iPhone 16 Pro Max",
    "iPhone 16 Pro",
    "iPhone 16 Plus",
    "iPhone 16",
    "iPhone 15 Pro Max",
    "iPhone 15 Pro",
    "iPhone 15 Plus",
    "iPhone 15",
    "iPhone 14 Pro Max",
    "iPhone 14 Pro",
    "iPhone 14 Plus",
    "iPhone 14",
    "iPhone SE (2022)",
    "iPhone 13 Pro Max",
    "iPhone 13 Pro",
    "iPhone 13",
    "iPhone 13 mini",
    "iPhone 12 Pro Max",
    "iPhone 12 Pro",
    "iPhone 12",
    "iPhone 12 mini",
    "iPhone SE (2020)",
    "iPhone 11 Pro Max",
    "iPhone 11 Pro",
    "iPhone 11",
    "iPhone XS Max",
    "iPhone XS",
    "iPhone XR",
    "iPhone X",
    "iPhone 8 Plus",
    "iPhone 8",
    "iPhone 7 Plus",
    "iPhone 7",
    "iPhone 6s Plus",
    "iPhone 6s",
    "iPhone SE (2016)",
  ],
  Samsung: [
    "Galaxy S26 Ultra",
    "Galaxy S26+",
    "Galaxy S26",
    "Galaxy Z Fold7",
    "Galaxy Z Flip7",
    "Galaxy S25 Ultra",
    "Galaxy S25 Edge",
    "Galaxy S25+",
    "Galaxy S25",
    "Galaxy S25 FE",
    "Galaxy Z Fold6",
    "Galaxy Z Flip6",
    "Galaxy S24 Ultra",
    "Galaxy S24+",
    "Galaxy S24",
    "Galaxy S24 FE",
    "Galaxy Z Fold5",
    "Galaxy Z Flip5",
    "Galaxy S23 Ultra",
    "Galaxy S23+",
    "Galaxy S23",
    "Galaxy S23 FE",
    "Galaxy Z Fold4",
    "Galaxy Z Flip4",
    "Galaxy S22 Ultra",
    "Galaxy S22+",
    "Galaxy S22",
    "Galaxy S21 Ultra",
    "Galaxy S21+",
    "Galaxy S21",
    "Galaxy S21 FE",
    "Galaxy Note20 Ultra",
    "Galaxy Note20",
    "Galaxy S20 Ultra",
    "Galaxy S20+",
    "Galaxy S20",
    "Galaxy S20 FE",
    "Galaxy Note10+",
    "Galaxy Note10",
    "Galaxy S10+",
    "Galaxy S10",
    "Galaxy S10e",
    "Galaxy Note9",
    "Galaxy S9+",
    "Galaxy S9",
    "Galaxy Note8",
    "Galaxy S8+",
    "Galaxy S8",
    "Galaxy A56",
    "Galaxy A36",
    "Galaxy A55",
    "Galaxy A54",
    "Galaxy A35",
    "Galaxy A53",
    "Galaxy A34",
    "Galaxy A25",
    "Galaxy A15",
    "Galaxy A14",
    "Galaxy A13",
  ],
  Google: [
    "Pixel 10 Pro Fold",
    "Pixel 10 Pro XL",
    "Pixel 10 Pro",
    "Pixel 10",
    "Pixel 9a",
    "Pixel 9 Pro Fold",
    "Pixel 9 Pro XL",
    "Pixel 9 Pro",
    "Pixel 9",
    "Pixel 8a",
    "Pixel 8 Pro",
    "Pixel 8",
    "Pixel Fold",
    "Pixel 7a",
    "Pixel 7 Pro",
    "Pixel 7",
    "Pixel 6a",
    "Pixel 6 Pro",
    "Pixel 6",
    "Pixel 5a",
    "Pixel 5",
    "Pixel 4a (5G)",
    "Pixel 4a",
    "Pixel 4 XL",
    "Pixel 4",
  ],
  OnePlus: [
    "OnePlus 13",
    "OnePlus 13R",
    "OnePlus 12",
    "OnePlus 12R",
    "OnePlus 11",
    "OnePlus 11R",
    "OnePlus Nord 4",
    "OnePlus 10 Pro",
    "OnePlus 10T",
    "OnePlus Nord 3",
    "OnePlus 9 Pro",
    "OnePlus 9",
    "OnePlus 8 Pro",
    "OnePlus 8T",
    "OnePlus 8",
    "OnePlus 7T Pro",
    "OnePlus 7T",
    "OnePlus 7 Pro",
    "OnePlus 7",
  ],
  Motorola: [
    "Motorola Razr Ultra (2025)",
    "Motorola Razr+ (2025)",
    "Motorola Razr (2025)",
    "Motorola Edge 60 Pro",
    "Motorola Edge 60",
    "Motorola Edge 50 Ultra",
    "Motorola Edge 50 Pro",
    "Motorola Edge 50",
    "Motorola Razr 40 Ultra",
    "Motorola Razr 40",
    "Moto G85",
    "Moto G84",
    "Moto G75",
    "Moto G55",
    "Moto G Power (2024)",
    "Moto G Stylus (2024)",
  ],
  Xiaomi: [
    "Xiaomi 15 Ultra",
    "Xiaomi 15",
    "Xiaomi 14 Ultra",
    "Xiaomi 14",
    "Xiaomi 13 Pro",
    "Xiaomi 13",
    "Redmi Note 14 Pro",
    "Redmi Note 13 Pro",
    "Redmi Note 12",
    "Poco F6",
    "Poco F5",
    "Poco X6",
  ],
  Oppo: [
    "Oppo Find X8 Pro",
    "Oppo Find X8",
    "Oppo Find X7 Ultra",
    "Oppo Reno 12",
    "Oppo Reno 11",
    "Oppo A98",
  ],
  Sony: [
    "Xperia 1 VII",
    "Xperia 10 VII",
    "Xperia 1 VI",
    "Xperia 5 V",
    "Xperia 10 VI",
    "Xperia 1 V",
  ],
  Nokia: ["Nokia G42", "Nokia X30", "Nokia G60", "Nokia XR21", "Nokia C32"],
  Asus: ["ROG Phone 9", "ROG Phone 8", "Zenfone 11 Ultra", "Zenfone 10", "Zenfone 9"],
  LG: ["LG V60 ThinQ", "LG Wing", "LG Velvet", "LG G8 ThinQ"],
};

/** Models for a brand (case-insensitive), newest → oldest. Empty if unknown. */
export function modelsForBrand(brand: string): string[] {
  const key = PHONE_BRANDS.find((b) => b.toLowerCase() === brand.trim().toLowerCase());
  return key ? PHONE_MODELS[key] ?? [] : [];
}
